export const books = [
  { title: "Notes from Underground", author: "Fyodor Dostoevsky" },
  { title: "Grendel", author: "John Gardner" },
  { title: "As I Lay Dying", author: "William Faulkner" },
  { title: "Hunger", author: "Knut Hamsun" },
  { title: "Lolita", author: "Vladimir Nabokov" },
  { title: "Mrs. Dalloway", author: "Virginia Woolf" },
  { title: "The Crying of Lot 49", author: "Thomas Pynchon" },
  { title: "The Rings of Saturn", author: "W.G. Sebald" },
  { title: "Normal People", author: "Sally Rooney" },
  { title: "Invisible Cities", author: "Italo Calvino" },
  { title: "Bluets", author: "Maggie Nelson" },
];

export const movies = [
  { title: "Mulholland Drive", year: 2001 },
  { title: "Vertigo", year: 1958 },
  { title: "Bringing Up Baby", year: 1938 },
  { title: "Trust", year: 1990 },
  { title: "Asako I & II", year: 2018 },
  { title: "Days of Heaven", year: 1978 },
  { title: "Mad Max: Fury Road", year: 2015 },
  { title: "Twin Peaks: The Return", year: 2017 },
  { title: "A Separation", year: 2011 },
  { title: "The Apartment", year: 1960 },
  { title: "Before Sunset", year: 2004 },
  { title: "Spacy", year: 1981 },
  { title: "Sweet Smell of Success", year: 1957 },
  { title: "The Social Network", year: 2010 },
  { title: "What's Up, Doc?", year: 1972 },
  { title: "Don't Go Breaking My Heart", year: 2011 },
  { title: "The Unbelievable Truth", year: 1989 },
  { title: "Metropolitan", year: 1990 },
  { title: "In a Lonely Place", year: 1950 },
  { title: "Charade", year: 1963 },
  { title: "Paterson", year: 2016 },
  { title: "Visage", year: 2009 },
  { title: "Once Upon a Time in the West", year: 1968 },
  { title: "The Handmaiden", year: 2016 },
  { title: "Broadcast News", year: 1987 },
  { title: "The Marriage of Maria Braun", year: 1979 },
  { title: "His Girl Friday", year: 1940 },
  { title: "Knives Out", year: 2019 },
  { title: "Solaris", year: 1972 },
  { title: "Through the Forest", year: 2005 },
  { title: "The Hole", year: 1998 },
  { title: "Sleeping Beauty", year: 2011 },
  { title: "La La Land", year: 2016 },
  { title: "Mission: Impossible \u2013 Rogue Nation", year: 2015 },
  { title: "The Grand Budapest Hotel", year: 2014 },
  { title: "Kill Bill: Vol. 1", year: 2003 },
  { title: "Harakiri", year: 1962 },
  { title: "One Battle After Another", year: 2025 },
  { title: "Some Like It Hot", year: 1959 },
  { title: "Touch of Evil", year: 1958 },
];
